import type { PrismaClient } from '../../src/generated/prisma/client'

import { SEED_IDS } from './ids'

export const seedMissions = async (prisma: PrismaClient) => {
  await prisma.mission.createMany({
    data: [
      // Module Base - Sprint 1
      {
        id: SEED_IDS.id_mission_article1_sprint1_moduleBase,
        moduleId: SEED_IDS.id_moduleBase,
        sprintId: SEED_IDS.id_sprint1_moduleBase,
        type: 'ARTICLE',
        difficulty: 'BEGINNER',
        title: 'Jak myśli komputer',
        shortDesc: 'Zrozumiesz, czym jest program, dane i podstawowe typy instrukcji.',
        description:
          'Artykuł wyjaśnia, jak komputer wykonuje instrukcje i dlaczego precyzja ma znaczenie. Fundament pod algorytmy i kod.',
        requirements: [],
        hints: [],
        etaMinutes: 7,
        xp: 12,
      },
      {
        id: SEED_IDS.id_mission_article2_sprint1_moduleBase,
        moduleId: SEED_IDS.id_moduleBase,
        sprintId: SEED_IDS.id_sprint1_moduleBase,
        type: 'ARTICLE',
        difficulty: 'BEGINNER',
        title: 'Algorytm i pseudokod',
        shortDesc: 'Nauczysz się rozpisywać rozwiązania krok po kroku zanim napiszesz kod.',
        description:
          'Artykuł pokazuje różnicę między zgadywaniem a algorytmem, uczy pseudokodu i rozbijania problemu na jednoznaczne kroki.',
        requirements: ['Program', 'Dane', 'Instrukcje'],
        hints: [],
        etaMinutes: 8,
        xp: 12,
      },
      {
        id: SEED_IDS.id_mission_quiz1_sprint1_moduleBase,
        moduleId: SEED_IDS.id_moduleBase,
        sprintId: SEED_IDS.id_sprint1_moduleBase,
        type: 'QUIZ',
        difficulty: 'BEGINNER',
        title: 'Quiz 1: Jak myśli komputer',
        shortDesc: 'Sprawdź, czy rozumiesz program, dane i instrukcje.',
        description:
          'Quiz weryfikuje podstawy: co komputer robi, czym są dane, instrukcje i gdzie najczęściej powstają błędy.',
        requirements: ['Program', 'Dane', 'Instrukcje'],
        hints: [],
        etaMinutes: 6,
        xp: 18,
        timeLimitSeconds: 360,
        passPercent: 75,
      },
      {
        id: SEED_IDS.id_mission_quiz2_sprint1_moduleBase,
        moduleId: SEED_IDS.id_moduleBase,
        sprintId: SEED_IDS.id_sprint1_moduleBase,
        type: 'QUIZ',
        difficulty: 'BEGINNER',
        title: 'Quiz 2: Algorytm i pseudokod',
        shortDesc: 'Sprawdź, czy potrafisz odróżnić algorytm od opisu „na oko”.',
        description: 'Quiz sprawdza rozumienie algorytmów, pseudokodu, jednoznaczności kroków i błędów logicznych.',
        requirements: ['Algorytm', 'Pseudokod'],
        hints: [],
        etaMinutes: 7,
        xp: 18,
        timeLimitSeconds: 420,
        passPercent: 75,
      },
      // Module Base - Sprint 2
      {
        id: SEED_IDS.id_mission_article1_sprint2_moduleBase,
        moduleId: SEED_IDS.id_moduleBase,
        sprintId: SEED_IDS.id_sprint2_moduleBase,
        type: 'ARTICLE',
        difficulty: 'BEGINNER',
        title: 'CPU, RAM, dysk i procesy',
        shortDesc: 'Zrozumiesz, co robi CPU, gdzie są dane i czym jest uruchomiony program.',
        description:
          'Artykuł tłumaczy podstawy działania komputera i systemu operacyjnego: CPU, RAM, dysk, proces oraz I/O. Daje praktyczną intuicję do debugowania zawieszek, problemów z pamięcią i zapisem danych.',
        requirements: ['Algorytm', 'Pseudokod'],
        hints: [],
        etaMinutes: 7,
        xp: 12,
      },
      {
        id: SEED_IDS.id_mission_quiz1_sprint2_moduleBase,
        moduleId: SEED_IDS.id_moduleBase,
        sprintId: SEED_IDS.id_sprint2_moduleBase,
        type: 'QUIZ',
        difficulty: 'BEGINNER',
        title: 'Quiz 3: Co dzieje się pod spodem',
        shortDesc: 'Sprawdź zrozumienie CPU, RAM, dysku, procesu i I/O.',
        description:
          'Quiz weryfikuje praktyczne podstawy działania programu: gdzie są dane, czym jest proces i dlaczego program często „czeka” zamiast „liczyć”.',
        requirements: ['CPU', 'RAM', 'Procesy', 'I/O'],
        hints: [],
        etaMinutes: 6,
        xp: 18,
        timeLimitSeconds: 360,
        passPercent: 75,
      },
      {
        id: SEED_IDS.id_mission_task1_sprint2_moduleBase,
        moduleId: SEED_IDS.id_moduleBase,
        sprintId: SEED_IDS.id_sprint2_moduleBase,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 1: Konkatenacja napisów',
        shortDesc: 'Połącz dwa napisy w jeden.',
        description:
          'Zaimplementuj funkcję solve(a, b), która przyjmuje dwa napisy i zwraca ich konkatenację (połączenie) w tej samej kolejności. Jeśli którykolwiek z napisów jest pusty, traktuj go jak pusty ciąg znaków.',
        requirements: ['Napisy', 'Operatory', 'return'],
        hints: ['W Pythonie napisy łączy się operatorem +.', 'Funkcja powinna zwrócić wynik, a nie go wypisywać.'],
        etaMinutes: 8,
        xp: 24,
        timeLimitSeconds: 480,
      },
      // Module Base - Sprint 3
      {
        id: SEED_IDS.id_mission_article1_sprint3_moduleBase,
        moduleId: SEED_IDS.id_moduleBase,
        sprintId: SEED_IDS.id_sprint3_moduleBase,
        type: 'ARTICLE',
        difficulty: 'BEGINNER',
        title: 'Od algorytmu do kodu: debug i testy',
        shortDesc: 'Składnia vs znaczenie, return vs print, scope i czytanie błędów.',
        description:
          'Artykuł buduje most między myśleniem algorytmicznym a pisaniem kodu: kontrakt funkcji, podstawy scope, czytanie komunikatów błędów oraz testowanie przypadków brzegowych.',
        requirements: ['Testy', 'Debug', 'return'],
        hints: [],
        etaMinutes: 8,
        xp: 12,
      },
      {
        id: SEED_IDS.id_mission_quiz1_sprint3_moduleBase,
        moduleId: SEED_IDS.id_moduleBase,
        sprintId: SEED_IDS.id_sprint3_moduleBase,
        type: 'QUIZ',
        difficulty: 'BEGINNER',
        title: 'Quiz 4: Most do kodu',
        shortDesc: 'Składnia vs znaczenie, return, scope, błędy i brzegowe testy.',
        description:
          'Quiz sprawdza podstawowe nawyki programisty: rozróżnianie błędów składni i logiki, poprawne zwracanie wartości z funkcji, scope, interpretację typowych wyjątków oraz myślenie o przypadkach brzegowych.',
        requirements: ['return', 'scope', 'Błędy'],
        hints: [],
        etaMinutes: 6,
        xp: 18,
        timeLimitSeconds: 360,
        passPercent: 75,
      },
      {
        id: SEED_IDS.id_mission_task1_sprint3_moduleBase,
        moduleId: SEED_IDS.id_moduleBase,
        sprintId: SEED_IDS.id_sprint3_moduleBase,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 1: Porównanie wartości',
        shortDesc: 'Sprawdź, czy a jest mniejsze lub równe b.',
        description:
          'Zaimplementuj funkcję solve(a, b), która zwraca wartość logiczną true, jeśli a jest mniejsze lub równe b. W przeciwnym przypadku funkcja powinna zwrócić false.',
        requirements: ['Porównania', 'Operatory', 'Boolean'],
        hints: ['Operator <= zwraca wartość logiczną.', 'Nie używaj print – zwróć wynik przez return.'],
        etaMinutes: 9,
        xp: 24,
        timeLimitSeconds: 540,
      },

      // Module Python Entry - Sprint 1
      {
        id: SEED_IDS.id_mission_article1_sprint1_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint1_modulePythonEntry,
        type: 'ARTICLE',
        difficulty: 'BEGINNER',
        title: 'Start w Pythonie: typy i operatory',
        shortDesc: 'Poznasz zmienne, typy danych i podstawowe operatory w Pythonie.',
        description:
          'Artykuł wprowadza w podstawy Pythona: zmienne, typy (int/float/str/bool), operatory arytmetyczne i porównania, konwersje typów oraz różnicę między return i print.',
        requirements: ['Podstawy programowania'],
        hints: [],
        etaMinutes: 7,
        xp: 12,
      },
      {
        id: SEED_IDS.id_mission_quiz1_sprint1_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint1_modulePythonEntry,
        type: 'QUIZ',
        difficulty: 'BEGINNER',
        title: 'Quiz 1: Typy i operatory',
        shortDesc: 'Sprawdź, czy rozumiesz typy, porównania i konwersje.',
        description:
          'Quiz weryfikuje podstawy: typy danych, różnice między stringiem a liczbą, operatory porównań, konwersje oraz użycie return w zadaniach funkcyjnych.',
        requirements: ['Typy', 'Operatory', 'return'],
        hints: [],
        etaMinutes: 6,
        xp: 18,
        timeLimitSeconds: 360,
        passPercent: 75,
      },
      {
        id: SEED_IDS.id_mission_task1_sprint1_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint1_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 1: Dodawanie',
        shortDesc: 'Zwróć sumę dwóch liczb.',
        description: 'Zaimplementuj solve(a, b), która zwraca sumę a + b.',
        requirements: ['Python podstawy', 'Operatory'],
        hints: ['Użyj operatora + i zwróć wynik przez return.'],
        etaMinutes: 8,
        xp: 22,
        timeLimitSeconds: 480,
      },
      {
        id: SEED_IDS.id_mission_task2_sprint1_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint1_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 2: Mnożenie',
        shortDesc: 'Policz pole prostokąta.',
        description: 'Zaimplementuj solve(width, height), która zwraca width * height.',
        requirements: ['Python podstawy', 'Operatory'],
        hints: ['Użyj operatora * i zwróć wynik przez return.'],
        etaMinutes: 8,
        xp: 22,
        timeLimitSeconds: 480,
      },
      {
        id: SEED_IDS.id_mission_task3_sprint1_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint1_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 3: Konwersja do string',
        shortDesc: 'Zamień liczbę na napis.',
        description: 'Zaimplementuj solve(n), która zwraca reprezentację n jako string (np. 10 → "10").',
        requirements: ['Python podstawy', 'Typy danych', 'Konwersje'],
        hints: ['Użyj str(n).'],
        etaMinutes: 9,
        xp: 22,
        timeLimitSeconds: 540,
      },
      {
        id: SEED_IDS.id_mission_bugfix1_sprint1_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint1_modulePythonEntry,
        type: 'BUGFIX',
        difficulty: 'BEGINNER',
        title: 'Bugfix 1: Dodawanie nie działa',
        shortDesc: 'Napraw funkcję, która miała dodawać.',
        description:
          'Funkcja solve(a, b) powinna zwracać sumę a + b, ale zwraca zły wynik. Popraw implementację tak, aby przechodziła testy.',
        requirements: ['Python podstawy', 'Operatory'],
        hints: ['Sprawdź, czy użyty operator odpowiada temu, co ma robić funkcja.'],
        etaMinutes: 9,
        xp: 24,
        timeLimitSeconds: 540,
      },
      {
        id: SEED_IDS.id_mission_bugfix2_sprint1_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint1_modulePythonEntry,
        type: 'BUGFIX',
        difficulty: 'BEGINNER',
        title: 'Bugfix 2: Dzielenie zwraca zły wynik',
        shortDesc: 'Napraw dzielenie tak, aby zwracało wynik zmiennoprzecinkowy.',
        description:
          'Funkcja solve(a, b) ma zwracać wynik dzielenia a / b, ale obecnie używa złego operatora i przechodzi w dzielenie całkowite. Popraw implementację tak, aby przechodziła testy.',
        requirements: ['Python podstawy', 'Operatory', 'Typy danych'],
        hints: ['W Pythonie / daje wynik float, a // daje dzielenie całkowite.'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },

      // Module Python Entry - Sprint 2
      {
        id: SEED_IDS.id_mission_article1_sprint2_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint2_modulePythonEntry,
        type: 'ARTICLE',
        difficulty: 'BEGINNER',
        title: 'Warunki i logika w Pythonie',
        shortDesc: 'Nauczysz się if/elif/else, porównań i operatorów logicznych.',
        description:
          'Artykuł wprowadza podejmowanie decyzji w kodzie: porównania zwracające True/False, instrukcje if/elif/else, operatory and/or/not oraz typowe pułapki jak zła kolejność warunków i mylenie = z ==.',
        requirements: ['Typy', 'Operatory', 'Porównania'],
        hints: [],
        etaMinutes: 7,
        xp: 12,
      },
      {
        id: SEED_IDS.id_mission_quiz1_sprint2_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint2_modulePythonEntry,
        type: 'QUIZ',
        difficulty: 'BEGINNER',
        title: 'Quiz 2: Warunki i logika',
        shortDesc: 'Sprawdź if/elif/else, porównania i operatory logiczne.',
        description:
          'Quiz weryfikuje poprawne rozumienie porównań, różnicy między = i ==, działania and/or/not oraz wpływu kolejności warunków w if/elif.',
        requirements: ['if', 'elif', 'else', 'Porównania'],
        hints: [],
        etaMinutes: 6,
        xp: 18,
        timeLimitSeconds: 360,
        passPercent: 75,
      },
      {
        id: SEED_IDS.id_mission_task1_sprint2_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint2_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 1: Porównanie <=',
        shortDesc: 'Zwróć true, jeśli a jest mniejsze lub równe b.',
        description:
          'Zaimplementuj solve(a, b), która zwraca wartość logiczną true, jeśli a <= b. W przeciwnym razie zwróć false.',
        requirements: ['Warunki', 'Porównania', 'Boolean'],
        hints: ['Użyj operatora <= i zwróć wynik (return).'],
        etaMinutes: 9,
        xp: 22,
        timeLimitSeconds: 540,
      },
      {
        id: SEED_IDS.id_mission_task2_sprint2_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint2_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 2: Sprawdź zakres',
        shortDesc: 'Zwróć true, jeśli x jest w przedziale [low, high].',
        description:
          'Zaimplementuj solve(x, low, high), która zwraca true, jeśli low <= x <= high. W przeciwnym razie zwróć false.',
        requirements: ['Warunki', 'Porównania', 'Operatory Logiczne'],
        hints: ['Użyj dwóch porównań połączonych and, albo zapisu low <= x <= high.'],
        etaMinutes: 10,
        xp: 22,
        timeLimitSeconds: 600,
      },
      {
        id: SEED_IDS.id_mission_task3_sprint2_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint2_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 3: Operator OR',
        shortDesc: 'Zwróć true, jeśli a > 0 lub b > 0.',
        description:
          'Zaimplementuj solve(a, b), która zwraca true, jeśli przynajmniej jedna z liczb (a lub b) jest większa od zera.',
        requirements: ['Warunki', 'Operatory Logiczne', 'Boolean'],
        hints: ['Użyj operatora or: (a > 0) or (b > 0).'],
        etaMinutes: 10,
        xp: 22,
        timeLimitSeconds: 600,
      },
      {
        id: SEED_IDS.id_mission_bugfix1_sprint2_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint2_modulePythonEntry,
        type: 'BUGFIX',
        difficulty: 'BEGINNER',
        title: 'Bugfix 1: Błąd w porównaniu',
        shortDesc: 'Funkcja ma obsługiwać równość, ale jej nie obsługuje.',
        description:
          'Funkcja solve(a, b) powinna zwracać true, gdy a jest mniejsze lub równe b. Aktualny kod błędnie traktuje równość jako false. Napraw implementację.',
        requirements: ['Warunki', 'Porównania', 'Boolean'],
        hints: ['Sprawdź, czy operator porównania uwzględnia równość.'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },
      {
        id: SEED_IDS.id_mission_bugfix2_sprint2_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint2_modulePythonEntry,
        type: 'BUGFIX',
        difficulty: 'BEGINNER',
        title: 'Bugfix 2: Zły operator logiczny',
        shortDesc: 'Kod wymaga obu warunków zamiast przynajmniej jednego.',
        description:
          'Funkcja solve(a, b) powinna zwracać true, jeśli a > 0 lub b > 0. Aktualny kod wymaga, aby oba były dodatnie. Zmień logikę tak, aby przechodziła testy.',
        requirements: ['Warunki', 'Operatory Logiczne', 'Boolean'],
        hints: ['To jest przypadek „przynajmniej jeden”, czyli or, nie and.'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },

      // Module Python Entry - Sprint 3
      {
        id: SEED_IDS.id_mission_article1_sprint3_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint3_modulePythonEntry,
        type: 'ARTICLE',
        difficulty: 'BEGINNER',
        title: 'Pętle i iteracja w Pythonie',
        shortDesc: 'Nauczysz się for, while, range i pracy na wielu elementach.',
        description:
          'Artykuł wprowadza pętle for i while, funkcję range(), iterację po danych oraz użycie break i continue. Celem jest poprawne przetwarzanie wielu elementów w kodzie.',
        requirements: ['Warunki', 'Porównania', 'Boolean'],
        hints: [],
        etaMinutes: 8,
        xp: 12,
      },
      {
        id: SEED_IDS.id_mission_quiz1_sprint3_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint3_modulePythonEntry,
        type: 'QUIZ',
        difficulty: 'BEGINNER',
        title: 'Quiz 3: Pętle',
        shortDesc: 'Sprawdź znajomość pętli for, while i range.',
        description:
          'Quiz sprawdza rozumienie pętli, działania range(), warunku zakończenia while oraz użycia break i continue.',
        requirements: ['Pętle', 'range', 'while'],
        hints: [],
        etaMinutes: 6,
        xp: 18,
        timeLimitSeconds: 360,
        passPercent: 75,
      },
      {
        id: SEED_IDS.id_mission_task1_sprint3_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint3_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 1: Suma 1..n',
        shortDesc: 'Policz sumę liczb od 1 do n.',
        description: 'Zaimplementuj solve(n), która zwraca sumę liczb całkowitych od 1 do n (włącznie).',
        requirements: ['Pętle', 'range', 'Operatory'],
        hints: ['Użyj pętli for i range(1, n+1).', 'Zacznij od total = 0 i dodawaj kolejne liczby.'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },
      {
        id: SEED_IDS.id_mission_task2_sprint3_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint3_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 2: Zlicz cyfry w tekście',
        shortDesc: 'Zwróć liczbę cyfr w stringu.',
        description: 'Zaimplementuj solve(s), która przechodzi po napisie i zlicza znaki będące cyframi (0-9).',
        requirements: ['Pętle', 'String', 'Warunki'],
        hints: ['Iteruj po znakach w s.', 'Sprawdź czy znak jest cyfrą (np. ch.isdigit()).'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },
      {
        id: SEED_IDS.id_mission_task3_sprint3_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint3_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 3: Suma elementów listy',
        shortDesc: 'Zwróć sumę liczb z listy.',
        description: 'Zaimplementuj solve(arr), która iteruje po liście liczb i zwraca sumę wszystkich elementów.',
        requirements: ['Pętle', 'Listy', 'Operatory'],
        hints: ['Użyj total = 0 i pętli for po elementach listy.'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },
      {
        id: SEED_IDS.id_mission_bugfix1_sprint3_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint3_modulePythonEntry,
        type: 'BUGFIX',
        difficulty: 'BEGINNER',
        title: 'Bugfix 1: Brakuje n w sumie',
        shortDesc: 'Kod liczy sumę 1..n, ale pomija ostatni element.',
        description:
          'Funkcja solve(n) ma zwracać sumę od 1 do n (włącznie). Aktualny kod ma błąd off-by-one i pomija n. Napraw pętlę.',
        requirements: ['Pętle', 'range', 'Operatory'],
        hints: ['Sprawdź granice range(). Żeby uwzględnić n, zwykle potrzebujesz n+1.'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },
      {
        id: SEED_IDS.id_mission_bugfix2_sprint3_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint3_modulePythonEntry,
        type: 'BUGFIX',
        difficulty: 'BEGINNER',
        title: 'Bugfix 2: while się nie kończy',
        shortDesc: 'Kod ma pętlę while bez kroku, przez co nie kończy działania.',
        description:
          'Funkcja solve(n) ma zwracać liczbę iteracji od 0 do n-1. Aktualny kod ma błąd i pętla while nie dochodzi do końca. Popraw implementację.',
        requirements: ['Pętle', 'while', 'Warunki'],
        hints: ['W pętli while musisz zmieniać zmienną sterującą (np. i += 1).'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },

      // Module Python Entry - Sprint 4
      {
        id: SEED_IDS.id_mission_article1_sprint4_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint4_modulePythonEntry,
        type: 'ARTICLE',
        difficulty: 'BEGINNER',
        title: 'Funkcje i scope w Pythonie',
        shortDesc: 'Zrozumiesz def, return, argumenty i gdzie żyją zmienne.',
        description:
          'Artykuł tłumaczy podstawy funkcji w Pythonie: definiowanie, wywołanie, argumenty (także domyślne), zwracanie wartości przez return oraz scope (zmienne lokalne vs globalne).',
        requirements: ['Pętle', 'range', 'while'],
        hints: [],
        etaMinutes: 8,
        xp: 12,
      },
      {
        id: SEED_IDS.id_mission_quiz1_sprint4_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint4_modulePythonEntry,
        type: 'QUIZ',
        difficulty: 'BEGINNER',
        title: 'Quiz 4: Funkcje i scope',
        shortDesc: 'Sprawdź return, argumenty domyślne i lokalność zmiennych.',
        description:
          'Quiz weryfikuje rozumienie funkcji: return, wartości domyślne argumentów, różnicę print vs return oraz podstawy scope.',
        requirements: ['Funkcje', 'return', 'Argumenty'],
        hints: [],
        etaMinutes: 6,
        xp: 18,
        timeLimitSeconds: 360,
        passPercent: 75,
      },
      {
        id: SEED_IDS.id_mission_task1_sprint4_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint4_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 1: Argument domyślny',
        shortDesc: 'Zwróć "prefix name", gdzie prefix ma wartość domyślną.',
        description: 'Zaimplementuj solve(name, prefix="Hi"), która zwraca napis w formacie "prefix name".',
        requirements: ['Funkcje', 'Argumenty', 'String'],
        hints: ['Użyj wartości domyślnej argumentu prefix.', 'Zwróć wynik przez return.'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },
      {
        id: SEED_IDS.id_mission_task2_sprint4_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint4_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 2: Większa liczba',
        shortDesc: 'Zwróć większą z dwóch liczb.',
        description: 'Zaimplementuj solve(a, b), która zwraca większą z dwóch liczb. Jeśli są równe, zwróć tę wartość.',
        requirements: ['Funkcje', 'Warunki', 'Porównania'],
        hints: ['Użyj if albo wbudowanego porównania.', 'Zwróć wynik, nie wypisuj go.'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },
      {
        id: SEED_IDS.id_mission_task3_sprint4_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint4_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 3: Dwa wyniki',
        shortDesc: 'Zwróć sumę i iloczyn dwóch liczb.',
        description: 'Zaimplementuj solve(a, b), która zwraca dwa wyniki: sumę a+b oraz iloczyn a*b.',
        requirements: ['Funkcje', 'Operatory', 'Tuple'],
        hints: ['Możesz zwrócić tuple (sum_, prod) lub listę [sum_, prod] zależnie od platformy.'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },
      {
        id: SEED_IDS.id_mission_bugfix1_sprint4_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint4_modulePythonEntry,
        type: 'BUGFIX',
        difficulty: 'BEGINNER',
        title: 'Bugfix 1: print zamiast return',
        shortDesc: 'Funkcja wypisuje wynik, ale nie zwraca wartości.',
        description:
          'Funkcja solve(a, b) ma zwracać sumę a+b. Aktualny kod używa print i zwraca None. Popraw implementację, aby przechodziła testy.',
        requirements: ['Funkcje', 'return', 'Operatory'],
        hints: ['Zamiast print użyj return.'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },
      {
        id: SEED_IDS.id_mission_bugfix2_sprint4_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint4_modulePythonEntry,
        type: 'BUGFIX',
        difficulty: 'BEGINNER',
        title: 'Bugfix 2: Zła wartość domyślna',
        shortDesc: 'Funkcja ma zły domyślny prefix.',
        description:
          'Funkcja solve(name, prefix="Hi") ma mieć domyślną wartość prefix ustawioną na "Hi". Aktualny kod ma inną wartość. Popraw implementację.',
        requirements: ['Funkcje', 'Argumenty', 'String'],
        hints: ['Sprawdź wartość domyślną argumentu prefix.'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },

      // Module Python Entry - Sprint 5
      {
        id: SEED_IDS.id_mission_article1_sprint5_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint5_modulePythonEntry,
        type: 'ARTICLE',
        difficulty: 'BEGINNER',
        title: 'Kolekcje w Pythonie',
        shortDesc: 'Listy, tuple, dict i set — podstawy i dobór struktury danych.',
        description:
          'Artykuł wprowadza podstawowe kolekcje Pythona: listy, krotki, słowniki i zbiory. Pokazuje typowe operacje oraz kiedy której struktury używać.',
        requirements: ['Pętle', 'Funkcje'],
        hints: [],
        etaMinutes: 9,
        xp: 12,
      },
      {
        id: SEED_IDS.id_mission_quiz1_sprint5_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint5_modulePythonEntry,
        type: 'QUIZ',
        difficulty: 'BEGINNER',
        title: 'Quiz 5: Kolekcje',
        shortDesc: 'Sprawdź list, tuple, dict i set.',
        description:
          'Quiz weryfikuje rozumienie podstawowych kolekcji Pythona: właściwości list/tuple, mapowanie w dict, unikalność w set oraz bezpieczne pobieranie wartości z dict.',
        requirements: ['Listy', 'Tuple', 'Dict', 'Set'],
        hints: [],
        etaMinutes: 6,
        xp: 18,
        timeLimitSeconds: 360,
        passPercent: 75,
      },
      {
        id: SEED_IDS.id_mission_task1_sprint5_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint5_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 1: Długość listy',
        shortDesc: 'Zwróć liczbę elementów listy.',
        description: 'Zaimplementuj solve(arr), która zwraca liczbę elementów w liście.',
        requirements: ['Listy', 'Kolekcje', 'Python podstawy'],
        hints: ['Użyj len(arr).'],
        etaMinutes: 9,
        xp: 24,
        timeLimitSeconds: 540,
      },
      {
        id: SEED_IDS.id_mission_task2_sprint5_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint5_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 2: Bezpieczne pobieranie z dict',
        shortDesc: 'Zwróć d[key] albo default, jeśli klucza nie ma.',
        description:
          'Zaimplementuj solve(d, key, default), która zwraca wartość dla podanego klucza, a jeśli klucz nie istnieje — zwraca wartość domyślną.',
        requirements: ['Dict', 'Kolekcje', 'Warunki'],
        hints: ['Użyj d.get(key, default) albo sprawdź: if key in d.'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },
      {
        id: SEED_IDS.id_mission_task3_sprint5_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint5_modulePythonEntry,
        type: 'TASK',
        difficulty: 'BEGINNER',
        title: 'Zadanie 3: Usuń duplikaty',
        shortDesc: 'Usuń duplikaty z listy, zachowując kolejność.',
        description:
          'Zaimplementuj solve(arr), która zwraca nową listę bez duplikatów, zachowując kolejność pierwszego wystąpienia elementów.',
        requirements: ['Listy', 'Set', 'Pętle'],
        hints: ['Trzymaj set „widzianych” elementów i buduj wynikową listę.'],
        etaMinutes: 12,
        xp: 24,
        timeLimitSeconds: 720,
      },
      {
        id: SEED_IDS.id_mission_bugfix1_sprint5_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint5_modulePythonEntry,
        type: 'BUGFIX',
        difficulty: 'BEGINNER',
        title: 'Bugfix 1: Zła długość listy',
        shortDesc: 'Funkcja zwraca zaniżoną długość listy.',
        description:
          'Funkcja solve(arr) ma zwracać liczbę elementów listy, ale obecny kod ma błąd off-by-one. Popraw implementację tak, aby przechodziła testy.',
        requirements: ['Listy', 'Kolekcje', 'Python podstawy'],
        hints: ['Jeśli używasz len(arr), nie odejmuj 1.'],
        etaMinutes: 9,
        xp: 24,
        timeLimitSeconds: 540,
      },
      {
        id: SEED_IDS.id_mission_bugfix2_sprint5_modulePythonEntry,
        moduleId: SEED_IDS.id_modulePythonEntry,
        sprintId: SEED_IDS.id_sprint5_modulePythonEntry,
        type: 'BUGFIX',
        difficulty: 'BEGINNER',
        title: 'Bugfix 2: Sprawdzanie klucza w dict',
        shortDesc: 'Kod sprawdza nie to, co trzeba i powoduje błędy.',
        description:
          'Funkcja solve(d, key, default) ma zwracać wartość dla klucza, a jeśli go nie ma — default. Aktualny kod sprawdza występowanie w wartościach (values), co jest błędne. Popraw implementację.',
        requirements: ['Dict', 'Kolekcje', 'Warunki'],
        hints: ['Klucze sprawdzasz: if key in d, a nie w d.values().'],
        etaMinutes: 10,
        xp: 24,
        timeLimitSeconds: 600,
      },
    ],
    skipDuplicates: true,
  })
}
