import type { PrismaClient } from '../../src/generated/prisma/client'

import { SEED_IDS } from './ids'

export const seedTasks = async (prisma: PrismaClient) => {
  await prisma.task.createMany({
    data: [
      // module base
      // sprint 2
      {
        missionId: SEED_IDS.id_mission_task1_sprint2_moduleBase,
        starterCode: 'def solve(a, b):\n return 0\n',
        language: 'python',
        tests: [
          { input: ['hello', 'world'], expectedOutput: 'helloworld' },
          { input: ['foo', 'bar'], expectedOutput: 'foobar' },
          { input: ['a', 'b'], expectedOutput: 'ab' },
          { input: ['e', ''], expectedOutput: 'e' },
          { input: ['super', 'John'], expectedOutput: 'superJohn' },
          { input: ['foo', 'bar'], expectedOutput: 'foobar' },
          { input: ['a', 'ib'], expectedOutput: 'aib' },
          { input: ['', 'a'], expectedOutput: 'a' },
        ],
      },
      // sprint 3
      {
        missionId: SEED_IDS.id_mission_task1_sprint3_moduleBase,
        starterCode: 'def solve(a, b):\n    return 0\n',
        language: 'python',
        tests: [
          { input: [1, 2], expectedOutput: true },
          { input: [2, 2], expectedOutput: true },
          { input: [3, 2], expectedOutput: false },
          { input: [222, 300], expectedOutput: true },
          { input: [11, 9], expectedOutput: false },
          { input: [11, 12], expectedOutput: true },
          { input: [100, -10], expectedOutput: false },
          { input: [-2, -1], expectedOutput: true },
        ],
      },
      // module python entry
      // sprint 1
      {
        missionId: SEED_IDS.id_mission_task1_sprint1_modulePythonEntry,
        starterCode: 'def solve(a, b):\n return 0\n',
        language: 'python',
        tests: [
          { input: [2, 3], expectedOutput: 5 },
          { input: [0, 0], expectedOutput: 0 },
          { input: [-2, 5], expectedOutput: 3 },
          { input: [10, -7], expectedOutput: 3 },
          { input: [-5, -6], expectedOutput: -11 },
          { input: [999, 1], expectedOutput: 1000 },
          { input: [1, 999], expectedOutput: 1000 },
          { input: [123456, 654321], expectedOutput: 777777 },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_task2_sprint1_modulePythonEntry,
        starterCode: 'def solve(width, height):\n return 0\n',
        language: 'python',
        tests: [
          { input: [2, 3], expectedOutput: 6 },
          { input: [5, 1], expectedOutput: 5 },
          { input: [0, 10], expectedOutput: 0 },
          { input: [7, 4], expectedOutput: 28 },
          { input: [1, 0], expectedOutput: 0 },
          { input: [9, 9], expectedOutput: 81 },
          { input: [12, 11], expectedOutput: 132 },
          { input: [100, 200], expectedOutput: 20000 },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_task3_sprint1_modulePythonEntry,
        starterCode: 'def solve(n):\n    return 0\n',
        language: 'python',
        tests: [
          { input: [10], expectedOutput: '10' },
          { input: [0], expectedOutput: '0' },
          { input: [-7], expectedOutput: '-7' },
          { input: [12345], expectedOutput: '12345' },
          { input: [1], expectedOutput: '1' },
          { input: [-1], expectedOutput: '-1' },
          { input: [999999], expectedOutput: '999999' },
          { input: [-999999], expectedOutput: '-999999' },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_bugfix1_sprint1_modulePythonEntry,
        starterCode: 'def solve(a, b):\n    return a - b\n',
        language: 'python',
        tests: [
          { input: [2, 3], expectedOutput: 5 },
          { input: [0, 0], expectedOutput: 0 },
          { input: [-2, 5], expectedOutput: 3 },
          { input: [10, -7], expectedOutput: 3 },
          { input: [-5, -6], expectedOutput: -11 },
          { input: [999, 1], expectedOutput: 1000 },
          { input: [1, 999], expectedOutput: 1000 },
          { input: [123456, 654321], expectedOutput: 777777 },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_bugfix2_sprint1_modulePythonEntry,
        starterCode: 'def solve(a, b):\n    return a // b\n',
        language: 'python',
        tests: [
          { input: [5, 2], expectedOutput: 2.5 },
          { input: [10, 4], expectedOutput: 2.5 },
          { input: [3, 2], expectedOutput: 1.5 },
          { input: [8, 4], expectedOutput: 2.0 },
          { input: [1, 2], expectedOutput: 0.5 },
          { input: [7, 2], expectedOutput: 3.5 },
          { input: [9, 3], expectedOutput: 3.0 },
          { input: [100, 8], expectedOutput: 12.5 },
        ],
      },
      // sprint 2
      {
        missionId: SEED_IDS.id_mission_task1_sprint2_modulePythonEntry,
        starterCode: 'def solve(a, b):\n return 0\n',
        language: 'python',
        tests: [
          { input: [1, 2], expectedOutput: true },
          { input: [2, 2], expectedOutput: true },
          { input: [3, 2], expectedOutput: false },
          { input: [0, 0], expectedOutput: true },
          { input: [-1, 0], expectedOutput: true },
          { input: [0, -1], expectedOutput: false },
          { input: [-5, -5], expectedOutput: true },
          { input: [-4, -5], expectedOutput: false },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_task2_sprint2_modulePythonEntry,
        starterCode: 'def solve(x, low, high):\n return 0\n',
        language: 'python',
        tests: [
          { input: [5, 1, 10], expectedOutput: true },
          { input: [1, 1, 10], expectedOutput: true },
          { input: [10, 1, 10], expectedOutput: true },
          { input: [0, 1, 10], expectedOutput: false },
          { input: [11, 1, 10], expectedOutput: false },
          { input: [-3, -5, -1], expectedOutput: true },
          { input: [-6, -5, -1], expectedOutput: false },
          { input: [-1, -5, -1], expectedOutput: true },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_task3_sprint2_modulePythonEntry,
        starterCode: 'def solve(a, b):\n return 0\n',
        language: 'python',
        tests: [
          { input: [1, 0], expectedOutput: true },
          { input: [0, 1], expectedOutput: true },
          { input: [1, 2], expectedOutput: true },
          { input: [0, 0], expectedOutput: false },
          { input: [-1, 0], expectedOutput: false },
          { input: [0, -1], expectedOutput: false },
          { input: [-1, 2], expectedOutput: true },
          { input: [2, -1], expectedOutput: true },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_bugfix1_sprint2_modulePythonEntry,
        starterCode: 'def solve(a, b):\n return a < b\n',
        language: 'python',
        tests: [
          { input: [1, 2], expectedOutput: true },
          { input: [2, 2], expectedOutput: true },
          { input: [3, 2], expectedOutput: false },
          { input: [0, 0], expectedOutput: true },
          { input: [-1, 0], expectedOutput: true },
          { input: [0, -1], expectedOutput: false },
          { input: [-5, -5], expectedOutput: true },
          { input: [-4, -5], expectedOutput: false },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_bugfix2_sprint2_modulePythonEntry,
        starterCode: 'def solve(a, b):\n    return (a > 0) and (b > 0)\n',
        language: 'python',
        tests: [
          { input: [1, 0], expectedOutput: true },
          { input: [0, 1], expectedOutput: true },
          { input: [1, 2], expectedOutput: true },
          { input: [0, 0], expectedOutput: false },
          { input: [-1, 0], expectedOutput: false },
          { input: [0, -1], expectedOutput: false },
          { input: [-1, 2], expectedOutput: true },
          { input: [2, -1], expectedOutput: true },
        ],
      },
      // sprint 3
      {
        missionId: SEED_IDS.id_mission_task1_sprint3_modulePythonEntry,
        starterCode: 'def solve(n):\n    return 0\n',
        language: 'python',
        tests: [
          { input: [1], expectedOutput: 1 },
          { input: [2], expectedOutput: 3 },
          { input: [3], expectedOutput: 6 },
          { input: [4], expectedOutput: 10 },
          { input: [5], expectedOutput: 15 },
          { input: [10], expectedOutput: 55 },
          { input: [50], expectedOutput: 1275 },
          { input: [100], expectedOutput: 5050 },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_task2_sprint3_modulePythonEntry,
        starterCode: 'def solve(s):\n    return 0\n',
        language: 'python',
        tests: [
          { input: ['a1b2c3'], expectedOutput: 3 },
          { input: ['123'], expectedOutput: 3 },
          { input: ['abc'], expectedOutput: 0 },
          { input: ['0'], expectedOutput: 1 },
          { input: [''], expectedOutput: 0 },
          { input: ['a0b0c'], expectedOutput: 2 },
          { input: ['9-8-7'], expectedOutput: 3 },
          { input: ['room42'], expectedOutput: 2 },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_task3_sprint3_modulePythonEntry,
        starterCode: 'def solve(arr):\n    return 0\n',
        language: 'python',
        tests: [
          { input: [[1, 2, 3]], expectedOutput: 6 },
          { input: [[0, 0, 0]], expectedOutput: 0 },
          { input: [[-1, -2, -3]], expectedOutput: -6 },
          { input: [[5]], expectedOutput: 5 },
          { input: [[10, -10]], expectedOutput: 0 },
          { input: [[2, 2, 2, 2]], expectedOutput: 8 },
          { input: [[100, 200, 300]], expectedOutput: 600 },
          { input: [[-5, 10, -5, 10]], expectedOutput: 10 },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_bugfix1_sprint3_modulePythonEntry,
        starterCode: 'def solve(n):\n    total = 0\n    for i in range(1, n):\n        total += i\n    return total\n',
        language: 'python',
        tests: [
          { input: [1], expectedOutput: 1 },
          { input: [2], expectedOutput: 3 },
          { input: [3], expectedOutput: 6 },
          { input: [4], expectedOutput: 10 },
          { input: [5], expectedOutput: 15 },
          { input: [10], expectedOutput: 55 },
          { input: [50], expectedOutput: 1275 },
          { input: [100], expectedOutput: 5050 },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_bugfix2_sprint3_modulePythonEntry,
        starterCode:
          'def solve(n):\n    i = 0\n    count = 0\n    while i < n:\n        count += 1\n    return count\n',
        language: 'python',
        tests: [
          { input: [0], expectedOutput: 0 },
          { input: [1], expectedOutput: 1 },
          { input: [2], expectedOutput: 2 },
          { input: [3], expectedOutput: 3 },
          { input: [5], expectedOutput: 5 },
          { input: [10], expectedOutput: 10 },
          { input: [25], expectedOutput: 25 },
          { input: [100], expectedOutput: 100 },
        ],
      },
      // sprint 4
      {
        missionId: SEED_IDS.id_mission_task1_sprint4_modulePythonEntry,
        starterCode: 'def solve(name, prefix="Hi"):\n    return 0\n',
        language: 'python',
        tests: [
          { input: ['Ala'], expectedOutput: 'Hi Ala' },
          { input: ['Ola'], expectedOutput: 'Hi Ola' },
          { input: ['Jan'], expectedOutput: 'Hi Jan' },
          { input: ['Ala', 'Cześć'], expectedOutput: 'Cześć Ala' },
          { input: ['Kasia', 'Hej'], expectedOutput: 'Hej Kasia' },
          { input: ['', 'Hi'], expectedOutput: 'Hi ' },
          { input: ['X', 'Yo'], expectedOutput: 'Yo X' },
          { input: ['Piotr'], expectedOutput: 'Hi Piotr' },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_task2_sprint4_modulePythonEntry,
        starterCode: 'def solve(a, b):\n    return 0\n',
        language: 'python',
        tests: [
          { input: [1, 2], expectedOutput: 2 },
          { input: [2, 1], expectedOutput: 2 },
          { input: [0, 0], expectedOutput: 0 },
          { input: [-1, 5], expectedOutput: 5 },
          { input: [5, -1], expectedOutput: 5 },
          { input: [-10, -3], expectedOutput: -3 },
          { input: [100, 99], expectedOutput: 100 },
          { input: [7, 7], expectedOutput: 7 },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_task3_sprint4_modulePythonEntry,
        starterCode: 'def solve(a, b):\n    return 0\n',
        language: 'python',
        tests: [
          { input: [2, 3], expectedOutput: [5, 6] },
          { input: [0, 5], expectedOutput: [5, 0] },
          { input: [-2, 3], expectedOutput: [1, -6] },
          { input: [10, -7], expectedOutput: [3, -70] },
          { input: [1, 1], expectedOutput: [2, 1] },
          { input: [4, 4], expectedOutput: [8, 16] },
          { input: [-5, -6], expectedOutput: [-11, 30] },
          { input: [100, 0], expectedOutput: [100, 0] },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_bugfix1_sprint4_modulePythonEntry,
        starterCode: 'def solve(a, b):\n    print(a + b)\n',
        language: 'python',
        tests: [
          { input: [2, 3], expectedOutput: 5 },
          { input: [0, 0], expectedOutput: 0 },
          { input: [-2, 5], expectedOutput: 3 },
          { input: [10, -7], expectedOutput: 3 },
          { input: [-5, -6], expectedOutput: -11 },
          { input: [999, 1], expectedOutput: 1000 },
          { input: [1, 999], expectedOutput: 1000 },
          { input: [123456, 654321], expectedOutput: 777777 },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_bugfix2_sprint4_modulePythonEntry,
        starterCode: 'def solve(name, prefix="Hello"):\n    return prefix + " " + name\n',
        language: 'python',
        tests: [
          { input: ['Ala'], expectedOutput: 'Hi Ala' },
          { input: ['Ola'], expectedOutput: 'Hi Ola' },
          { input: ['Jan'], expectedOutput: 'Hi Jan' },
          { input: ['Ala', 'Cześć'], expectedOutput: 'Cześć Ala' },
          { input: ['Kasia', 'Hej'], expectedOutput: 'Hej Kasia' },
          { input: ['', 'Hi'], expectedOutput: 'Hi ' },
          { input: ['X', 'Yo'], expectedOutput: 'Yo X' },
          { input: ['Piotr'], expectedOutput: 'Hi Piotr' },
        ],
      },
      // sprint 5
      {
        missionId: SEED_IDS.id_mission_task1_sprint5_modulePythonEntry,
        starterCode: 'def solve(arr):\n    return 0\n',
        language: 'python',
        tests: [
          { input: [[1, 2, 3]], expectedOutput: 3 },
          { input: [[]], expectedOutput: 0 },
          { input: [[0]], expectedOutput: 1 },
          { input: [[1, 1, 1, 1]], expectedOutput: 4 },
          { input: [[-1, -2]], expectedOutput: 2 },
          { input: [[10, 20, 30, 40, 50]], expectedOutput: 5 },
          { input: [[7, 8, 9, 10, 11, 12]], expectedOutput: 6 },
          { input: [[100]], expectedOutput: 1 },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_task2_sprint5_modulePythonEntry,
        starterCode: 'def solve(d, key, default):\n    return 0\n',
        language: 'python',
        tests: [
          { input: [{ a: 1 }, 'a', 0], expectedOutput: 1 },
          { input: [{ a: 1 }, 'b', 0], expectedOutput: 0 },
          { input: [{ x: 'ok' }, 'x', 'no'], expectedOutput: 'ok' },
          { input: [{ x: 'ok' }, 'y', 'no'], expectedOutput: 'no' },
          { input: [{}, 'a', 123], expectedOutput: 123 },
          { input: [{ k: 0 }, 'k', 7], expectedOutput: 0 },
          { input: [{ z: null }, 'z', 'd'], expectedOutput: null },
          { input: [{ p: true }, 'p', false], expectedOutput: true },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_task3_sprint5_modulePythonEntry,
        starterCode: 'def solve(arr):\n    return 0\n',
        language: 'python',
        tests: [
          { input: [[1, 2, 2, 3]], expectedOutput: [1, 2, 3] },
          { input: [[1, 1, 1]], expectedOutput: [1] },
          { input: [[]], expectedOutput: [] },
          { input: [[5, 4, 5, 4, 3]], expectedOutput: [5, 4, 3] },
          { input: [[0, 0, 1, 0]], expectedOutput: [0, 1] },
          { input: [[2, 3, 2, 3, 2]], expectedOutput: [2, 3] },
          { input: [[-1, -1, -2, -1]], expectedOutput: [-1, -2] },
          { input: [[9, 8, 7]], expectedOutput: [9, 8, 7] },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_bugfix1_sprint5_modulePythonEntry,
        starterCode: 'def solve(arr):\n    return len(arr) - 1\n',
        language: 'python',
        tests: [
          { input: [[1, 2, 3]], expectedOutput: 3 },
          { input: [[]], expectedOutput: 0 },
          { input: [[0]], expectedOutput: 1 },
          { input: [[1, 1, 1, 1]], expectedOutput: 4 },
          { input: [[-1, -2]], expectedOutput: 2 },
          { input: [[10, 20, 30, 40, 50]], expectedOutput: 5 },
          { input: [[7, 8, 9, 10, 11, 12]], expectedOutput: 6 },
          { input: [[100]], expectedOutput: 1 },
        ],
      },
      {
        missionId: SEED_IDS.id_mission_bugfix2_sprint5_modulePythonEntry,
        starterCode:
          'def solve(d, key, default):\n    if key in d.values():\n        return d[key]\n    return default\n',
        language: 'python',
        tests: [
          { input: [{ a: 1 }, 'a', 0], expectedOutput: 1 },
          { input: [{ a: 1 }, 'b', 0], expectedOutput: 0 },
          { input: [{ x: 'ok' }, 'x', 'no'], expectedOutput: 'ok' },
          { input: [{ x: 'ok' }, 'y', 'no'], expectedOutput: 'no' },
          { input: [{}, 'a', 123], expectedOutput: 123 },
          { input: [{ k: 0 }, 'k', 7], expectedOutput: 0 },
          { input: [{ z: null }, 'z', 'd'], expectedOutput: null },
          { input: [{ p: true }, 'p', false], expectedOutput: true },
        ],
      },
    ],
    skipDuplicates: true,
  })
}
